version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQAScafoldingProject
  gitServerName: siqagituser
  gitUrl: https://github.com/siqagituser/SIQAScafoldingProject
  gitUsername: siqagituser
  gitBranch: main
- name: WmJDBCAdapter
  wpmServer: https://packages.webmethods.io
  wpmRegistry: softwareag
services:
- serviceName: project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:DatabaseNewAcc
  packages:
  - name: SIQAScafoldingProject
    version: "1.0"
- serviceName: project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:DBInsert
  packages:
  - name: SIQAScafoldingProject
    version: "1.0"
- serviceName: project.siqascafolding.integrations:SIQAAdapterFlow
  packages:
  - name: SIQAScafoldingProject
    version: "1.0"
- serviceName: project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:DBNewInsert
  packages:
  - name: SIQAScafoldingProject
    version: "1.0"
- serviceName: project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:Database_2
  packages:
  - name: SIQAScafoldingProject
    version: "1.0"
configurationVariables:
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.user
  : sa
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.networkProtocol
  : tcp
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.trustStore
  : ""
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionManagerSettings.maximumPoolSize
  : "20"
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.transactionType
  : LOCAL_TRANSACTION
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionSettings.dbType
  : MSSQL
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionManagerSettings.expireTimeout
  : "5000"
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionSettings.trustStore
  : ""
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionEnabled
  : "false"
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.minimumPoolSize
  : "1"
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.keyStore
  : ""
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionSettings.password
  : "{AES}B2Xqma4Ost5nVUiXctJydQ=="
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.serverName
  : vmiboint01
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.dbType
  : MSSQL
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.password
  : "{AES}B2Xqma4Ost5nVUiXctJydQ=="
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionSettings.transactionType
  : LOCAL_TRANSACTION
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.otherProperties
  : loginTimeout=60;driverType=thin;
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionEnabled
  : "false"
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionManagerSettings.minimumPoolSize
  : "1"
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionSettings.portNumber
  : "1433"
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionSettings.driverType
  : Progress速 DataDirect速
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.portNumber
  : "1433"
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionManagerSettings.poolable
  : "true"
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.maximumPoolSize
  : "20"
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.expireTimeout
  : "5000"
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionManagerSettings.blockingTimeout
  : "5000"
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.poolable
  : "true"
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.datasourceClass
  : com.wm.dd.jdbcx.sqlserver.SQLServerDataSource
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.blockingTimeout
  : "5000"
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionSettings.serverName
  : vmiboint01
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionSettings.user
  : sa
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionSettings.keyStore
  : ""
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionSettings.datasourceClass
  : com.wm.dd.jdbcx.sqlserver.SQLServerDataSource
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionSettings.networkProtocol
  : tcp
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionSettings.databaseName
  : SIQACloud
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.driverType
  : Progress速 DataDirect速
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionSettings.otherProperties
  : loginTimeout=60;driverType=thin;
  ? artConnection.SIQAScafoldingProject.project.siqascafolding.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.databaseName
  : SIQACloud
